### ISSUE TITLE
How can I connect this to chat?

### ISSUE THREAD

**Issue by kman1459** [urgrue/Java-Twitch-Api-Wrapper#11]
I want it to me connected to chat but the only option I see when I do it is Chat Badges.

twitch.chat().getBadges(channel, handler);

can someone help me I can post more code if need be.

Thanks,
Kman

**Comment by rinagonics** [comment]
Hello! I've been using this API for my own bot and I've the same issue, my workaround is this:

    ```
public List<User> getViewersInChannel() {
            try {
                List<User> list = new ArrayList<>();
                JSONObject users = null;
                try {
                    users = HTTP.getHttp().getRequest("https://tmi.twitch.tv/group/user/ringoshiba/chatters");
                } catch (RuntimeException re) {
                    re.printStackTrace();
                }
                JSONArray chatters = users.getJSONObject("chatters").getJSONArray("viewers");
                for (int i = 0; i < chatters.length(); i++) {
//do something with the viewers
                }
                JSONArray moderators = users.getJSONObject("chatters").getJSONArray("moderators");
                for (int i = 0; i < moderators.length(); i++) {
//do something with the moderators
                }
                return list;
            } catch (IOException | SQLException e) {
                e.printStackTrace();
            }
        return null;
    }
```

Note that the HTTP request (which doesnt need authentication) could return an HTTP error because  the API is flakey/getting a lot of requests so you'll need to handle a retry mechanism in this method.

Hope this helps! Even though it was a month ago that you posted :P

**Comment by rinagonics** [comment]
Wow i totally misread your question the first time I was writing a reply.

Take a look at PircBotX. It can do everything you need for the TwitchChat

**Comment by Gikkman** [comment]
Like rinagonics wrote, this project won't help you send messages to chat. Check out PircBot if you want to send messages to the irc chat.

**Comment by kman1459** [comment]
Wow thank you both for replying. I did find Pircbot a while ago but have not figured out a way for it to reply to everyone. At the moment it only PMs itself so being the novice programmer I am pretty confused atm.

**Comment by Gikkman** [comment]
No problems. 

You can check out some tutorials on PircBot. There area a few on actually making Twitch Bots. Just google: "PricBot Twitch". It might be a bit slow to read tutorials but believe me, it is the best way for understanding what is going on and how the library works.
