### ISSUE TITLE
Get Current Viewer Count

### ISSUE THREAD

**Issue by kman1459** [urgrue/Java-Twitch-Api-Wrapper#15]
I don't if this should be under Pull request but can someone update the code for it to be possible to get the current viewer count. I ain't an expert programmer and don't know how to add code to GitHub projects...

**Comment by Gikkman** [comment]
You can already get the number of viewers from the API.

`Twitch t = new Twitch();
//Get token and all that
twitch.streams().get(channel, new StreamResponseHandler() {
   @Override
   public void onSuccess(Stream stream) {
      //Make sure stream is not null here
      int viewers = stream.getViewers();	
   }
} );`

Something like that.

**Comment by kman1459** [comment]
Thanks Man!!! @Gikkman
