### ISSUE TITLE
How can I get the follower count method to return a int

### ISSUE THREAD

**Issue by kman1459** [urgrue/Java-Twitch-Api-Wrapper#16]
Here is my problem I want to have the Current follower count to print to a jframe gui and I cant get my variables to leave the method Code

//Number of Follows
        twitch.channels().getFollows("crysyn", new ChannelFollowsResponseHandler() {

```
        @Override
        public void onFailure(int statusCode, String statusMessage, String errorMessage) {
            //Twitch API responded with an error message
        }

        @Override
        public void onFailure(Throwable e) {
            //Unable to access Twitch, or error parsing the response
        }

        @Override
        public void onSuccess(int arg0, List<ChannelFollow> arg1) {
            System.out.println("Follower Count: " + arg0);
            //Useless but fun
            //System.out.println("Names: " + arg1);
            //so it can do how many followers you start and finish with
            String Follow1 = Integer.toString(arg0);
        }
        });
```

Code for GUI

//Make the GUI thing
    public main() {
        getContentPane().setBackground(Color.WHITE);
        setForeground(Color.WHITE);
        getContentPane().setForeground(Color.WHITE);
        getContentPane().setLayout(null);

```
    JLabel lblFollowersStart = new JLabel("Followers Start");
    lblFollowersStart.setFont(new Font("Verdana", Font.BOLD, 13));
    lblFollowersStart.setBounds(10, 45, 135, 14);
    getContentPane().add(lblFollowersStart);


    FollowS = new JTextField();
    FollowS.setText(Follow1);
    FollowS.setForeground(Color.WHITE);
    FollowS.setFont(new Font("Verdana", Font.BOLD, 13));
    FollowS.setBounds(20, 70, 86, 20);
    getContentPane().add(FollowS);
    FollowS.setColumns(10);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setBounds(100, 100, 534, 397);
}
```

I want to get Follow1 into the gui thing

Thanks for the HELP

**Comment by Gikkman** [comment]
This is not a tech support forum. The Issues section is for problems related to the library, not for answering general Java questions. 

Try to google: "java return from response handle" or "java return from async method", or check out StackOverflow

And please close the previous issues we've answered for you.
